### ISSUE TITLE
network_id instead of vlan_id - source for network_id

### ISSUE THREAD

**Issue by tonymarsh** [paultyng/terraform-provider-unifi#103]
HI,
Apologies if this is answered already, but with vlan_id being depreciated, what should a valid network_id string look like under the unifi_wlan resource?
I've tried a case sensitive string matching the "name" being applied to the network, and variations there of, but haven't had any luck. 
Tips very appreciated!

**Comment by paultyng** [comment]
You can see an updated example here: https://github.com/paultyng/terraform-provider-unifi/pull/75/files

The easiest way to do this is pull the `id` attribute from the `unifi_network` resource. To find this information in the UI is a bit harder as you probably need to look at the raw JSON data to find it.
