### ISSUE TITLE
WLAN Schedule

### ISSUE THREAD

**Issue by mabunixda** [paultyng/terraform-provider-unifi#14]
Hi,

in your sdk i am not able to get a clue how wlan scheduling is configureable :( 
Do you get an idea about this?

Thanks, Martin

**Comment by paultyng** [comment]
Your best bet is to connect to the controller over IP address and look at the XHR requests to see what the JSON looks like behind the scenes from the UI. Then you can just emulate that in the SDK/provider.

**Comment by mabunixda** [comment]
Ok, [another lib](https://github.com/unifi-poller/unifi) is using a approach of getting the json from the API and convert it to golang structs. I tried to get stuff into that but in the meantime your projects poped up :-) 
On the javascript variants a implementation seems to [include this info]{https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L2884} .. i gonna try to get PR on the run

**Comment by paultyng** [comment]
The string slice in the browser seems to get values like this, an array of times to block off:

```json
"schedule": ["tue|0000-0900", "tue|2000-2400", "thu|0715-1430"],
```

So you could just build those strings manually, or update the structs in go-unifi to handle it a bit more cleanly.

**Comment by paultyng** [comment]
I think for the HCL you could do something like:

```terraform
resource "unifi_wlan" "test" {
  schedule {
    day_of_week = "tue"
    block_start    = "00:00"
    block_end     = "9:00"
  }
}
```

**Comment by paultyng** [comment]
If you can PR great, if not, I'll add this to my list as well for some time in the next few weeks.
