### ISSUE TITLE
Cannot set WPA3 types for security on wlan

### ISSUE THREAD

**Issue by ukd1** [paultyng/terraform-provider-unifi#154]
```
% terraform apply       
╷
│ Error: expected security to be one of [wpapsk wpaeap open], got wpa3psk
│ 
│   with unifi_wlan.wifi_sec,
│   on unifi.tf line 140, in resource "unifi_wlan" "wifi_sec":
│  140:   security          = "wpa3psk"
│ 
```

https://github.com/paultyng/terraform-provider-unifi/blob/main/internal/provider/resource_wlan.go#L53 seems to be the source of the restriction.

However, in the UI I see:

<img width="824" alt="image" src="https://user-images.githubusercontent.com/44345/125002310-81169380-e009-11eb-975f-d78cc46512f5.png">

**Comment by paultyng** [comment]
Trying to figure this one out. I also see this in the UI but didn't see the data in the scripts really. Need to play around in a test controller and just observe what it sends back and forth for each one.

**Comment by paultyng** [comment]
Turns out its different fields that control this. security should still be set to `wpapsk` but you can turn on WPA3 support / transition as additional flags. I've put up a PR to add this: #179
