### ISSUE TITLE
Sites are resources / data of a unifi provider, not a provider level config

### ISSUE THREAD

**Issue by marcoceppi** [paultyng/terraform-provider-unifi#16]
I think there needs to be a shift to how the provider is configured. Instead of setting the site at the provider configuration portion it seems more apt to instead have resources that are attached to sites, have sites as data/resource options, and allow management of multiple objects between sites in one workspace.

**Comment by paultyng** [comment]
@marcoceppi this mostly grew out of how the API works. Almost every API endpoint requires a site, so its easier to not have to specify it everywhere. Also, I wrote this for my home network, which didn't quite illustrate the UX challenges for me. I could change this to an "override" model where you can specify a default site at provider level and override on a resource by resource level. 

Alternatively, depending on your number of sites, you can just instantiate a provider multiple times and alias it, this is how people handle multiple regions in AWS, etc.  But if you want to iterate a list of sites, I can see how that could be problematic until support for that is added.

**Comment by marcoceppi** [comment]
We've started using aliases, but I'd be happy to add the features to make it so sites become a resource which can be tagged on items (where default is just assumed if not specified)

**Comment by paultyng** [comment]
👍 I'd accept that PR.

**Comment by marcoceppi** [comment]
Great, I'll start working on it and propose something early next week <3

**Comment by kurtmc** [comment]
@marcoceppi Did you get anywhere with this? I am pretty keen to start managing sites in terraform and this provider looks like a good starting point, I would be happy to implement the site resource.

**Comment by marcoceppi** [comment]
We paused our efforts to focus elsewhere on our stack. Unifi managed by terraform is still important (25 sites and growing) I don't have a lot of work from this to show so of you wanted to take over this issue go for it!

**Comment by paultyng** [comment]
I think this is now supported in v0.18.0-beta.1. Going to take it for a spin for a while and add some additional testing hopefully over the next couple weeks.
