### ISSUE TITLE
Add darwin_amd64 to releases?

### ISSUE THREAD

**Issue by woneill** [paultyng/terraform-provider-unifi#17]
I was able to successfully build and use the darwin_amd64 binary built using `goreleaser` and the config already in the repo. Can you add this platform to your release process?

Thanks!

**Comment by paultyng** [comment]
I think it is already? Are you not able to use the one attached to the release?

![image](https://user-images.githubusercontent.com/422474/78559867-20375480-77e3-11ea-9609-60c0f327fd21.png)

**Comment by woneill** [comment]
Gah! I dunno how I missed it originally- perhaps I was thinking `osx` when I was looking at the releases list?

I'll close this out and use the release 😁

FWIW- I'm absolutely loving this provider. I was able to import most of my existing configuration into it and have started setting up VLANs which I'd been putting off. Being able to preview the changes in terraform has been a big help!
