### ISSUE TITLE
Question: How are the test.auto.tfvars files used

### ISSUE THREAD

**Issue by micahlmartin** [paultyng/terraform-provider-unifi#180]
I'm trying to figure out how the test.auto.tfvars are being used. I'm building a Terraform provider and this project was listed as a reference in the terraform-plugin-docs utility. I was able to see how to create example usage files, but it's not clear what is being done with the test.auto.tfvars files. Thanks in advance!

**Comment by paultyng** [comment]
I use those to just manually test the example dirs occasionally. So `cd` to the dir, run `terraform apply`, etc. (and the normal [.auto.tfvars](https://www.terraform.io/docs/language/values/variables.html#variable-definitions-tfvars-files) rules apply). I had played around with additional automation to do this in PRs, etc., but haven't gotten it fully working.
