### ISSUE TITLE
Support for `unifi_user` to set local dns record 

### ISSUE THREAD

**Issue by slessardjr** [paultyng/terraform-provider-unifi#272]
In the newer version of the console it allows us to override the DNS record for clients (`unifi_user`).  Allow this to be set with a resource (new or existing)

<img width="380" alt="UDM Screenshot for local dns entry." src="https://user-images.githubusercontent.com/6098292/189811537-e430f911-654a-4493-9609-c1931338b104.png">

**Comment by woneill** [comment]
Support for this was added in #293 but there hasn't been a release generated with it yet.

@paultyng Is there anything I can do to help generate a release?

**Comment by joshuaspence** [comment]
I've just published v0.39.0
