### ISSUE TITLE
Enabling radius mac authentication for wlan with wpapsk

### ISSUE THREAD

**Issue by slangdaddy** [paultyng/terraform-provider-unifi#274]
Is it possible to enabled "RADIUS MAC authentication" using this provider?

I found there is the property "radius_profile_id", which sets the radius profile to be used, but from the docs it seems only to be related to wpaeap.
My use case is to have wpapsk authentication for clients and assign the right network / vlan using radius. I had to manually enable "RADIUS MAC authentication" in the UI for this. Doing latter did not lead to any change when running terraform plan afterwards. So it appears that this switch is not implemented in this provider (?)

**Comment by paultyng** [comment]
Some additional RADIUS resources were merged in [v0.36.0](https://github.com/paultyng/terraform-provider-unifi/releases/tag/v0.36.0) but I don't think it covers the MAC use case yet.
