### ISSUE TITLE
Is it possible to configure static routes?

### ISSUE THREAD

**Issue by queglay** [paultyng/terraform-provider-unifi#42]
Very cool project!  I frequently spin up openvpn instances for each gitlab pipeline test.  Would it be possible to somehow configure static routes with your provider api?

**Comment by paultyng** [comment]
Hey, sorry for the delayed response, missed this in other notifications. If its in the controller UI I should be able to manage it here, but I haven't added it yet, I'll take a peek soon and see if its possible to add it.

**Comment by queglay** [comment]
Thanks Paul for considering it :)

**Comment by paultyng** [comment]
I just added this to go-unifi, the main issue I'm running in to with implementation is I haven't found an easy way to fake adoption of a USG in the docker controller. So I can't test some of this stuff yet. I hopefully will have something workable within a week or so but may need some help testing. Not sure if you could give example routes you need to configure here to test with?

**Comment by queglay** [comment]
I'm sorry Paul I only have a unifi but no USG currently, I'm planning on buying one soon after I move.  I dont think this will be possible for me to test until I get a USG.

**Comment by paultyng** [comment]
Created this issue as well to investigate the emulation of a USG: https://github.com/paultyng/terraform-provider-unifi/issues/49

**Comment by paultyng** [comment]
This will be released in v0.25.0

**Comment by queglay** [comment]
Thanks for adding this ability!
