### ISSUE TITLE
Contributing and Testing

### ISSUE THREAD

**Issue by JalfResi** [paultyng/terraform-provider-unifi#64]
Hi! I've been working on a small branch of changes to implement some of the WAN settings for my own Unifi homelab (USG + Cloud Key + WIFI AP + More) but I feel like I'm stumbling at the final hurdle - I've implemented the necessary changes, written tests, and the test suite passes - but I can't seem to test the plugin on my own setup at home! When I copy the resulting binary from the ~/.terraform/plugins directory into ~/Projects/homelab/.terraform/plugins/registry.terraform.io/paultyng/unifi/0.15.0-beta.1/darwin_amd64/terraform-provider-unifi_v0.15.0-beta.1 I get the following terraform error message:

> Error: unable to determine API URL style: Get "": unsupported protocol scheme ""

regardless of the terraform action I take (plan, apply, import, etc), and even with clearing my terraform state and re-running terraform init (which just redownloads from the registry).

I feel like I've missed something fundamental - how can I test my local build of the plugin against my local homelab terrafrom files?

**Comment by paultyng** [comment]
Do you have an example of your provider configuration (or are you setting the `UNIFI_API` env var)? 

It probably should validate it earlier, but it looks like you are just getting an empty string for the API base URL in there.

**Comment by JalfResi** [comment]
Gah! I'm such an idiot! I thought it was something I'd done when making changes to the plugin, but it was UNIFI_API not being set. Thanks for quick response - proper kicking myself!

I should have a pull request available soon to cover basic WAN settings (specifically for PPPOE)
