### ISSUE TITLE
please add example to unifi_firewall_rule how to use more complex rules

### ISSUE THREAD

**Issue by rkoosaar** [paultyng/terraform-provider-unifi#78]
In the GUI I can set:
 
Source type = Addres/PortGroup
IPv4 Address Group = Any
Port Group = Any

(same options for destination)
How do I do this with the the provider? Is it possible?

In the GUI I can set:

Source type = Network 
Network = Name of Network (is this the src_network_id or dst_network_id?)

**Comment by rkoosaar** [comment]
I've worked it out.

**Comment by paultyng** [comment]
Happy to add other examples in the docs if you have some suggestions. I also have a few different network / VLAN modules I hope to publish soon I've been using myself that may give people some ideas.

**Comment by rkoosaar** [comment]
I've actually created a module which I published to terraform registry. I have some examples there.
