### ISSUE TITLE
unifi_wlan resource

### ISSUE THREAD

**Issue by rkoosaar** [paultyng/terraform-provider-unifi#83]
I've been updating my unifi controller module to include the unifi_wlan resource. I've been trying to get the scheduling to work.

Well, it works but only for a specific day. I didn't find a way to do it for multiple days.

If I include this in my terraform config, it works:
      ~ schedule {
          ~ block_end   = "2:45"
          ~ block_start = "2:00"
          ~ day_of_week = "sun"
        }
So I changed the config from the web gui and set it accross multiple days and than did terraform plan again which revealed this:
      ~ schedule {
          ~ block_end   = "2:45" -> "11:01"
          ~ block_start = "2:00" -> "12:00"
          ~ day_of_week = "mon-sun" -> "sun"
        }

I noticed that you only support single days. Is it possible to change day_of_week to support this value > "mon-sun"  or a similar combination?

**Comment by paultyng** [comment]
Yeah, I can relax the validation, let me see if its easy enough.

You could also write it as something like this I think:

```terraform
schedule {
  block_end = "2:45"
  block_start = "2:00"
  day_of_week = "mon"
}

schedule {
  block_end = "2:45"
  block_start = "2:00"
  day_of_week = "tue"
}

schedule {
  block_end = "2:45"
  block_start = "2:00"
  day_of_week = "sun"
}

# ...
```

**Comment by paultyng** [comment]
Or as a dynamic block:

```terraform
dynamic "schedule" {
  for_each = ["mon", "tue", "wed"]
  content {
    day_of_week = schedule.value
    block_start = "2:00"
    block_end = "2:45"
  }
}
```
```

**Comment by rkoosaar** [comment]
> Or as a dynamic block:
> 
> ```terraform
> dynamic "schedule" {
>   for_each = ["mon", "tue", "wed"]
>   content {
>     day_of_week = schedule.value
>     block_start = "2:00"
>     block_end = "2:45"
>   }
> }
> ```

I've actually done just that (before seeing your comment).
```terraform
 dynamic "schedule" {
    for_each = var.uw_schedule
    content {
      block_end = schedule.value.block_end
      block_start   = schedule.value.block_start
      day_of_week = schedule.value.day_of_week
    }
  }

variable "uw_schedule" {
  type = map(object({
    block_end   = string
    block_start = string
    day_of_week = string
  }))
  default = {}
}
```

this allows me to write it like so:

```terraform
 uw_schedule = {
    "Mon" = {
      block_end = "12:00",
      block_start = "10:00",
      day_of_week = "mon"
    },
    "Sat" = {
      block_end = "12:00",
      block_start = "10:00",
      day_of_week = "sat"
    }
  }
```

**Comment by paultyng** [comment]
Going to close this, but please let me know if there is some aspect of the scheduling that is still not working out for you and I can revisit it.
