### ISSUE TITLE
Allow importing with site name or ID

### ISSUE THREAD

**Issue by hanerd** [paultyng/terraform-provider-unifi#91]
I'm confused as to how to actually import a site.

The `id` is a computed value that doesn't exist until the site is created or imported, but it appears that ID is necessary to import the site.

Where do I find the `id` for the site in order to do an import?  Shouldn't it be the randomly generated "name" attribute from the Unifi Software?

**Comment by paultyng** [comment]
Unfortunately the way the import is written now, you need to use the ID the controller software assigns to the site. To get this you can either look in the dev console when in your controller UI, or potentially it would be in the backup / settings download for the site. I only have a single site on my home instance so haven't tested this though, I typically just use the dev console.

I think it would be useful to code the import to use the "name" though, so going to turn this in to a feature request to modify that import functionality to allow for both.

**Comment by jibbajabber** [comment]
Shame, I also have no way to get controller assigned ID to start using these resources either.
Dev console doesn't show anything helpful (all are >24 digits, none of which are recognised during import), Referer shows id for device under edit and no site id. 
Disappointing, great that it works for some, I was hoping to make use of this.
