### ISSUE TITLE
Indicate which controller versions the provider works with in the README.md

### ISSUE THREAD

**Issue by ErikEvenson** [paultyng/terraform-provider-unifi#96]
I'm planning on switching to the 6.x unifi controller.  Would be nice to understand how this provider works with 5.x vs. 6.x and what issues I might see upgrading.  Thanks for the nice tool!

**Comment by paultyng** [comment]
The acceptance testing tests against both [v5 and v6 versions of the controller](https://github.com/paultyng/terraform-provider-unifi/blob/e0df86374de2f8ad8182c09e3120634b98e92059/.github/workflows/acctest.yml#L45-L46). The usage is a bit different though depending on your version (AP groups vs WLAN groups for example).
